#include <fstream>
#include <random>

int main() {

    std::ofstream outputFile( "numbers.dat" );
    if( outputFile ) {

        std::random_device rd;  //Will be used to obtain a seed for the random number engine
        std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
        std::uniform_int_distribution<> dis(1, 500000);
    
        for (long int n{0}; n < 2000000; ++n) {
            //Use dis to transform the random unsigned int generated by gen into an int in [1, 500000]
            outputFile << dis(gen) << ' ';
        }
        outputFile << "-1\n";
    }
}